# Generated by Django 5.0.1 on 2024-02-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Clothes and Accessories', 'Clothes and Accessories'), ('Electronics', 'Electronics'), ('Home and living', 'Home and Living'), ('Books and stationery', 'Books and Stationery'), ('Sports and outdoors', 'Sports and Outdoors'), ('Beauty and cosmetics', 'Beauty and Cosmetics'), ('Toys and Games', 'Toys and games'), ('Pets and Pet Supplies', 'Pets and pet Supplies'), ('Home improvement', 'Home improvement')], max_length=50, null=True)),
                ('sub_category', models.CharField(choices=[("Men's Clothing", "Men's Clothing"), ("Women's Clothing", "Women's Clothing"), ('Kitchen', 'Kitchen'), ('Accessories', 'Accessories'), ('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Audio Device', 'Audio Device'), ('Furniture', 'Furniture'), ('Kitchen', 'Kitchen'), ('Decor', 'Decor'), ('Fiction', 'Fiction'), ('Novels', 'Novels'), ('Magazines', 'Magazines'), ('Outdoor Gear', 'Outdoor Gear'), ("Sport's Equipment", "Sport's Equipment"), ('Active Wear', 'Active Wear'), ('Makeup', 'Makeup'), ('Skincare', 'Skincare'), ('Haircare', 'Haircare'), ('Fragrance', 'Fragrance'), ("Children's Toys", "Children's Toys"), ('Board Games', 'Board Games'), ('Outdoor Games', 'Outdoor Games'), ('Video Games', 'Video Games'), ('Educational Toys', 'Educational Toys'), ('Puzzles', 'Puzzles'), ('Pet Food', 'Pet Food'), ('Toys and Accessories', 'Toys and Accessories'), ('Grooming and Health', 'Grooming and Health'), ('Pet Carries', 'Pet Carries'), ('Small Animal Supplies', 'Small Animal Supplies'), ('Power Tools', 'Power Tools'), ('Hand Tools', 'Hand Tools'), ('Painting Supplies', 'Painting Supplies'), ('Home Security', 'Home Security'), ('Lightning and Electrical', 'Lightning and Electrical'), ('Plumbing', 'Plumbing'), ('Hardware', 'Hardware'), ('Home Organization', 'Home Organization')], max_length=50, null=True)),
                ('sub_type_category', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Dresses', 'Dresses'), ('Tops', 'Tops'), ('Sweaters', 'Sweaters'), ('Buttons', 'Buttons'), ('Pants', 'Pants'), ('Leggins', 'Leggins'), ('Outwear', 'Outwear'), ('Hats', 'Hats'), ('Bags', 'Bags'), ('Scarves', 'Scarves'), ('Sunglasses', 'Sunglasses'), ('Jewelry', 'Jewelry'), ('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Mac', 'Mac'), ('Headphones', 'Headphones'), ('Speakers', 'Speakers'), ('Earphones', 'Earphones'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Dining Room', 'Dining Room'), ('Cookware', 'Cookware'), ('Cutlery', 'Cutlery'), ('Appliances', 'Appliances'), ('Wall Art', 'Wall Art'), ('Rugs', 'Rugs'), ('Nails and Screws', 'Nails and Screws'), ('Drills', 'Drills'), ('Dog Food', 'Dog Food'), ('Action Figures', 'Action Figures'), ('Face', 'Face'), ('Camping', 'Camping'), ('Mystery', 'Mystery')], max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(choices=[('Xtra Large', 'Xtra Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
